Feat pe u0 gve2
vladysllav/FitnessBot pull request #6
Opened 2023-08-11 14:09 UTC by nazya08

2023-08-16 17:37 UTC, AlexGrig23 approved these changes
LGFM

2023-08-16 17:45 UTC, UsovDmytro approved these changes

2023-08-16 17:46 UTC, VasylKonon approved these changes

2023-08-17 07:51 UTC, vitaliileonov approved these changes

2023-08-18 09:54 UTC, vladysllav commented on src/main.py
> -load_dotenv()
Why do we move that row to bottom?

2023-08-18 09:57 UTC, vladysllav commented on src/main.py
> +        self.user_service = UserService(CSVFileHandler(os.getenv("PATH_TO_DB")))
Do not use CSV handler in this way, better initialize it inside UserService

2023-08-18 10:00 UTC, vladysllav requested changes
1. CSV handler should work with users file for users and other files for other purposes, so create another file for user storing. 
2. Use SCV handler inside UserService, dont pass handler as arg to UserService, initialize that handler inside __init__ method of UserService

2023-08-22 12:28 UTC, closed without merging